### ISSUE TITLE
Oddzielenie trzech części

### ISSUE THREAD

**Issue by pikrol** [pikrol/CDI-adaptive#6]
Po każdej części ma być informacja o tym, że się ją zakończyło i przycisk? po którego kliknięciu rozpoczyna się kolejna (dotyczy SiGu).

**Comment by gkrajewski** [comment]
Tak, to dotyczy zasadniczo SIGu, przy czym zakładam, że zależy nam, jak
zawsze, na zgeneralizowanym mechanizmie. Np. jak jest więcej testów, to
dopiero ostatni kończy się tekstem z podziękowaniami, a wcześniejsze mają
przycisk "dalej". Niezależnie od liczby testów, każdy powinien zaczynać się
od wyświetlenia instrukcji, przy czym warto też pewnie dodać instrukcję
ogólną/wstęp. Taki wstęp i podziękowania mogłyby być zapisywane w pliku z
translacjami "ogólnymi" (w przeciwieństwie do treści pytań i instrukcji do
danego testu).

**Comment by so-sonia** [comment]
Dla każdego itemu powinna być podana w kolumnie obok instrukcja (tekst wprowadzający) z jakim ten item ma się wyświetlić. np. Czy Państwa dziecko wykonuje następujące czynności (i tu czynność).

Będzie jeden plik wsadowy z oddzielonymi częściami (przez dodatkową kolumnę na nazwę części).

Pozycja startowa każdej części zawsze na podstawie płci/wieku.

Komunikaty końcowe po każdej części podane w pliku z ustawieniami.

**Comment by so-sonia** [comment]
Czy theta początkowa (a więc także plik startThetas) powinna być ta sama dla każdej części czy różna dla każdej części? Jeśli to drugie to plik startThetas trzeba by rozszerzyć o podgrupy formularzy

**Comment by gkrajewski** [comment]
No chyba różna dla każdej części, bo każdą część traktujemy jako oddzielne narzędzie psychometryczne (zresztą w tradycyjnych "statycznych" CDIach też tak jest: są oddzielne normy dla wyników w każdej części): oddzielna analiza IRT i w konsekwencji oddzielne thety. Chyba że się mylę?

**Comment by pikrol** [comment]
Ja też myślę, że różna.

pon., 14 cze 2021 o 11:59 gkrajewski ***@***.***> napisał(a):

**Comment by so-sonia** [comment]
W pliku z itemami jest możliwość definiowanaia różnych części testu. Aplikacja działa także jeśli nie zdefiniowano żadnej grupy.
Wymagania:
- w pliku z itemami muszą sie znajdować kolumny: a1, d, item, question (czyli pytanie wprowadzające dla danego itema). Opcjonalnie może być zdefiniowana kolumna group.
- jeżeli test ma działać dla różnych grup w pliku translations.csv w polu "groups" nalezy podać wszystkie grupy oddzielone przecinkiem (co wazne, jeżeli grupy będą zdefiniowane tylko w items.csv, ale nie w pliku translations.csv, aplikacja potraktuje je, jakby były jedną grupą)
- każdą część może oddzielać komunikatem. Komunikat jest wyświetla się przy zmianie jednej grupy na drugą (więc nie wyświetla się ponownie, jeśli pierwsza grupa została zakończona, sesja zamknięta i ponownie otwarta, wtedy od razu aplikacja zacznie działać od grupy drugiej). Komunikat jest przyporządkowany po nazwie do grupy następującej, czyli jeżeli pierwsza grupa to "mowa", a druga to "rozumienie", komunikat znajduje się w pliku translations.csv pod nazwą rozumienieBtn. Żeby przejść do następnej części kilka się na przycisk z napisem zdefiniowanym w polu continueBtn w pliku translations.csv
